[project]
name = "fastbin"
version = "0.1.0"
description = "HTTPbin FastAPI implementation."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-watch>=4.2.0",
]
