
line-length = 100
indent-width = 4

target-version = "py313"


[lint]
select = [
    "A",    # flake8-builtins
    "ANN",  # flake8-annotations
    "ARG",  # flake8-unused-arguments
    "B",    # flake8-bugbear
    "BLE",  # flake8-blind-except
    "COM",  # flake8-commas
    "C4",   # flake8-comprehensions
    "C90",  # mccabe
    "D",    # pydocstyle
    "E",    # pycodestyle errors
    "ERA",  # eradicate
    "EM",   # flake8-errmsg
    "F",    # pyflakes
    "FAST", # FastAPI
    "FBT",  # flake8-boolean-trap
    "FIX",  # flake8-fixme
    "FLY",  # flynt
    "FURB", # refurb
    "G",    # flake8-logging-format
    "I",    # isort
    "ICN",  # flake8-import-conventions
    "INP",  # flake8-no-pep420
    "ISC",  # flake8-implicit-str-concat
    "N",    # pep8-naming
    "PERF", # Perflint
    "PIE",  # flake8-pie
    "PL",   # Pylint
    "PTH",  # flake8-use-pathlib
    "PT",   # flake8-pytest-style
    "RET",  # flake8-return
    "RSE",  # flake8-raise
    "RUF",  # Ruff-specific rules
    "S",    # flake8-bandit
    "SIM",  # flake8-simplify
    "SLF",  # flake8-self
    "TID",  # flake8-tidy-imports
    "TRY",  # tryceratops
    "T10",  # flake8-debugger
    "UP",   # pyupgrade
    "W",    # pycodestyle warnings
]

ignore = [
    "ANN204",  # missing-return-type-special-method
    "COM812",  # missing-trailing-comma
    "D100",    # missing docstring in public module
    "D104",    # missing docstring in public package
    "D106",    # missing docstring in public nested class
    "PLR0913", # too-many-arguments
    "W191",    # indentation contains tabs
    "ISC001",  # single-line-implicit-string-concatenation
]

fixable = ["ALL"]
unfixable = []

[lint.extend-per-file-ignores]
"{test*.py}" = [
    "ANN",    # flake8-annotations
    "INP001", # implicit-namespace-package
    "N802",   # invalid-function-name
    "PD901",  # pandas-df-variable-name
    "S",      # flake8-bandit
    "S301",   # suspicious-pickle-usage
    "SLF001", # private-member-access
]

"{**/migrations/*,admin.py,models.py,*serializers.py,*views.py}" = [
    "RUF012", # mutable-class-default
]
[lint.pydocstyle]
convention = "google"

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "cr-lf"


[lint.pycodestyle]
max-doc-length = 80
